"""
API Wrappers for NinjaRobot V5 — Blockly/SafeExecutor Interface.

This module provides high-level wrappers that expose a simple API
for user code generated by the Blockly visual programming IDE.

Available API (V5.2.1 - ±90° standardized):
    robot.servo[n].angle = x   - Set servo n (0-7) to angle x (±90°)
    robot.servos.move_pin(pin, angle, speed_mode="M") - Move a GPIO servo
    robot.servos.move_pins({pin: angle}, ...) - Move GPIO servos together
    robot.buzzer.tone(f, d)    - Play frequency f for d seconds
    robot.buzzer.play(name)    - Play emotion sound
    robot.buzzer.play_song(name) - Play a built-in melody
    robot.display.clear()      - Clear display
    robot.display.text(msg, ...) - Show static or scrolling text
    robot.expression(name)     - Show facial expression
    robot.distance.read()      - Read distance in mm
"""

from __future__ import annotations

import logging
import time
from pathlib import Path

from PIL import Image
from pi0disp.effects.text_ticker import TextTicker, render_centered_text_image

from .robot_sound import RobotSoundPlayer
from .facial_expressions import AnimatedFaces

log = logging.getLogger(__name__)

SERVO_ANGLE_MIN = -90
SERVO_ANGLE_MAX = 90
SERVO_CENTER_ANGLE = 0
SERVO_SPEED_MODES = frozenset({"F", "M", "S"})
SERVO_DEFAULT_SPEED_MODE = "M"


def _clamp_servo_angle(value, context: str) -> float:
    clamped_value = max(SERVO_ANGLE_MIN, min(SERVO_ANGLE_MAX, value))
    if clamped_value != value:
        log.warning(
            "%s requested out-of-range servo angle %s; clamped to %s",
            context,
            value,
            clamped_value,
        )
    return clamped_value


def _normalize_servo_speed_mode(value, context: str) -> str:
    mode = str(value or SERVO_DEFAULT_SPEED_MODE).upper()
    if mode not in SERVO_SPEED_MODES:
        log.warning(
            "%s requested invalid servo speed mode %s; using %s",
            context,
            value,
            SERVO_DEFAULT_SPEED_MODE,
        )
        return SERVO_DEFAULT_SPEED_MODE
    return mode


class DistanceWrapper:
    """Wrapper for VL53L0X distance sensor."""

    def __init__(self, sensor):
        self._sensor = sensor

    def read(self):
        """Returns distance in mm from VL53L0X sensor.
        
        Returns:
            int: Distance in millimeters. Returns 9999 if sensor unavailable.
        """
        if self._sensor:
            data = self._sensor.get_data()
            distance = data.get("distance_mm")
            if data.get("is_valid") is False or distance is None or distance < 0:
                log.warning("Distance read unavailable or invalid; returning 9999mm fallback")
                return 9999
            return distance
        return 9999


class BuzzerWrapper:
    """Wrapper for passive buzzer with emotion sounds."""

    def __init__(self, hal):
        self._hal = hal
        self._player = RobotSoundPlayer(hal)

    def play(self, sound_name):
        """Play a predefined emotion sound by name.
        
        Valid names: happy, sad, exciting, angry, confusing, cry, 
                     embarrassing, idle, laughing, scary, shy, 
                     sleepy, speaking, surprising
        """
        self._player.play(sound_name)

    def tone(self, frequency, duration):
        """Play a specific frequency tone.
        
        Args:
            frequency: Frequency in Hz (100-2000).
            duration: Duration in seconds.
        """
        if self._hal.buzzer:
            self._hal.buzzer.execute({"frequency": frequency, "duration": duration})

    def play_song(self, name):
        """Play a built-in melody by name."""
        if not self._hal.buzzer:
            return
        if not hasattr(self._hal.buzzer, "play_named_song"):
            log.warning("Built-in song playback is not available on the active buzzer driver.")
            return
        self.stop(restart_buzzer=True)
        self._hal.buzzer.play_named_song(name)

    def stop(self, restart_buzzer: bool = True):
        """Stop Blockly-triggered emotion sounds and keep buzzer usable."""
        self._player.stop(restart_buzzer=restart_buzzer)


class DisplayWrapper:
    """Wrapper for ST7789 display."""

    def __init__(self, hal, runtime_pipeline=None, cooperative_sleep=None):
        self._hal = hal
        self._runtime_pipeline = runtime_pipeline
        self._sleep = cooperative_sleep or time.sleep
        self._active_ticker = None
        self._search_paths = [
            Path(__file__).parent / "static" / "assets" / "images",
        ]

    def stop(self):
        """Stop any active scrolling text without clearing the display."""
        ticker = self._active_ticker
        self._active_ticker = None
        if ticker is None:
            return
        try:
            ticker.stop()
        except Exception as exc:
            log.warning("Failed to stop active text ticker: %s", exc)

    def image(self, name):
        """Display an image by name (e.g., 'star' -> 'star.png')."""
        if not self._hal.display:
            return
        self.stop()

        image_path = None
        for path in self._search_paths:
            for ext in [".png", ".jpg", ".bmp"]:
                candidate = path / f"{name}{ext}"
                if candidate.exists():
                    image_path = candidate
                    break
            if image_path:
                break

        if image_path:
            try:
                img = Image.open(image_path)
                self._hal.display.execute({"image": img})
            except Exception as e:
                log.error(f"Failed to load/display image {name}: {e}")
        else:
            log.warning(f"Image '{name}' not found in assets.")

    def clear(self, hold: bool = True):
        """Clear the display (fill with black)."""
        if self._hal.display:
            self.stop()
            self._hal.display.execute({"clear": True})
            if hold and self._runtime_pipeline:
                self._runtime_pipeline.mark_display_hold()

    def text(
        self,
        content,
        scroll: bool = False,
        duration: float = 2.0,
        speed: float = 2.0,
        language: str = "auto",
        font_size: int = 32,
        color: tuple[int, int, int] = (255, 255, 255),
        bg_color: tuple[int, int, int] = (0, 0, 0),
    ):
        """Display static or scrolling text for a cooperative duration."""
        if not self._hal.display:
            return

        display_duration = max(0.0, float(duration))
        text_value = str(content)
        self.stop()

        if scroll:
            ticker = TextTicker(
                self._hal.display,
                text_value,
                font_size=font_size,
                color=color,
                bg_color=bg_color,
                speed=speed,
                language=language,
            )
            self._active_ticker = ticker
            ticker.start()
            try:
                self._sleep(display_duration)
            finally:
                if self._active_ticker is ticker:
                    self._active_ticker = None
                ticker.stop()
            return

        image = render_centered_text_image(
            self._hal.display,
            text_value,
            font_size=font_size,
            color=color,
            bg_color=bg_color,
            language=language,
        )
        self._hal.display.execute({"image": image})
        self._sleep(display_duration)


class ServoWrapper:
    """Wrapper for a single servo motor.

    Uses ±90° angle range directly (V5.2.1 standardization).
    Center position is 0°, full range is -90° to +90°.
    """

    def __init__(self, multi_servo, index):
        self._multi_servo = multi_servo
        self._index = index
        self._angle = SERVO_CENTER_ANGLE  # Default to center (0°)

    @property
    def angle(self):
        """Get the current angle (±90°)."""
        return self._angle

    @angle.setter
    def angle(self, value):
        """Set the servo angle (±90°).

        No conversion needed - uses ±90° range directly.
        """
        value = _clamp_servo_angle(value, f"servo[{self._index}].angle")
        self._angle = value

        if self._multi_servo and hasattr(self._multi_servo, 'servo'):
            # Use move() with default blocking duration (0.5s)
            self.move(value, duration=0.5)
        else:
            log.warning("Servos not available")

    def move(self, angle: float, duration: float = 0.5):
        """Move this servo to angle over duration (blocking).

        Args:
            angle: Target angle (±90°).
            duration: Movement time in seconds (default 0.5).
        """
        angle = _clamp_servo_angle(angle, f"servo[{self._index}].move")
        self._angle = angle

        if self._multi_servo:
            try:
                # Construct list for ServoGroup.move_all_angles_sync
                # None = don't move other servos
                target_angles = [None] * 8
                if 0 <= self._index < 8:
                    target_angles[self._index] = angle  # No conversion needed
                    self._multi_servo.move_all_angles_sync(target_angles, move_sec=duration)
                else:
                    log.error(f"Servo index {self._index} out of range")
            except Exception as e:
                log.error(f"Failed to move servo {self._index}: {e}")


class ServoArrayWrapper:
    """Wrapper that provides list-like access to servos.

    Allows code like: robot.servo[0].angle = 45  (±90° range)
    """

    def __init__(self, multi_servo, count=8):
        self._multi_servo = multi_servo
        self._servos = [ServoWrapper(multi_servo, i) for i in range(count)]

    def __getitem__(self, index):
        """Get servo by index (0-7)."""
        if 0 <= index < len(self._servos):
            return self._servos[index]
        raise IndexError(f"Servo index {index} out of range (0-7)")

    def __len__(self):
        return len(self._servos)

    @property
    def pins(self) -> list[int]:
        """Get list of GPIO pins from underlying ServoGroup."""
        if self._multi_servo:
            return self._multi_servo.pins
        return []

    def get_all_angles(self) -> list[float]:
        """Get current angles from all servos."""
        if self._multi_servo:
            return self._multi_servo.get_all_angles()
        return [0.0] * len(self._servos)

    def move_pin(
        self,
        pin: int,
        angle: float,
        speed_mode: str = SERVO_DEFAULT_SPEED_MODE,
        easing: str = "ease_in_out_cubic",
    ) -> bool:
        """Move one servo by GPIO pin number using pi0servo speed modes."""
        return self.move_pins({pin: angle}, speed_mode=speed_mode, easing=easing)

    def move_pins(
        self,
        movements: dict[int, float],
        speed_mode: str = SERVO_DEFAULT_SPEED_MODE,
        per_servo_speeds: dict[int, str] | None = None,
        easing: str = "ease_in_out_cubic",
        force: bool = True,
    ) -> bool:
        """Move multiple GPIO-pin-addressed servos simultaneously.

        Args:
            movements: Mapping of GPIO pin number to target angle (-90 to 90).
            speed_mode: Global speed mode ("F", "M", or "S").
            per_servo_speeds: Optional mapping of GPIO pin to speed override.
            easing: Easing function name.
            force: Forward PWM even for tiny moves to avoid limp servos.

        Returns:
            True if completed, False if aborted.
        """
        if not self._multi_servo:
            return True

        ordered_pins = self.pins
        known_pins = set(ordered_pins)
        normalized_movements = {int(pin): angle for pin, angle in movements.items()}
        unknown_pins = sorted(pin for pin in normalized_movements if pin not in known_pins)
        if unknown_pins:
            raise ValueError(
                f"Servo GPIO pin(s) not configured: {unknown_pins}. "
                f"Configured pins: {ordered_pins}"
            )

        global_speed = _normalize_servo_speed_mode(speed_mode, "servos.move_pins")
        per_servo_speeds = {
            int(pin): _normalize_servo_speed_mode(speed, f"servos.move_pins[{pin}]")
            for pin, speed in (per_servo_speeds or {}).items()
        }
        unknown_speed_pins = sorted(pin for pin in per_servo_speeds if pin not in known_pins)
        if unknown_speed_pins:
            raise ValueError(
                f"Servo GPIO speed override pin(s) not configured: {unknown_speed_pins}. "
                f"Configured pins: {ordered_pins}"
            )

        target_angles: list[float | None] = []
        speed_modes: list[str] = []
        for pin in ordered_pins:
            if pin in normalized_movements:
                target_angles.append(
                    _clamp_servo_angle(
                        normalized_movements[pin],
                        f"servos.move_pins[{pin}]",
                    )
                )
                speed_modes.append(per_servo_speeds.get(pin, global_speed))
            else:
                target_angles.append(None)
                speed_modes.append(global_speed)

        try:
            return self._multi_servo.move_all_sync(
                target_angles,
                speed_mode=speed_modes,
                easing=easing,
                force=force,
            )
        except Exception as e:
            log.error(f"Failed to move_pins: {e}")
            return False

    def move_all_sync(
        self,
        targets: list[float | None],
        speed_mode: str | list[str] = "M",
        easing: str = "ease_out",
    ) -> bool:
        """Move all servos with per-servo speed control.

        Wrapper for ServoGroup.move_all_sync.

        Args:
            targets: List of target angles. None = don't move.
            speed_mode: Single mode or list of modes per servo.
            easing: Easing function name.

        Returns:
            True if completed, False if aborted.
        """
        if not self._multi_servo:
            return True

        try:
            return self._multi_servo.move_all_sync(
                targets, speed_mode=speed_mode, easing=easing
            )
        except Exception as e:
            log.error(f"Failed to move_all_sync: {e}")
            return False

    def move_all_angles(self, targets: list[float | None]):
        """Instant movement (no interpolation).

        Args:
            targets: List of target angles. None = don't move.
        """
        if self._multi_servo:
            try:
                self._multi_servo.move_all_angles(targets)
            except Exception as e:
                log.error(f"Failed to move_all_angles: {e}")

    def move_all(self, angles: list, duration: float = 0.5):
        """Move all servos simultaneously (legacy API).

        Args:
            angles (list): List of 8 angles (±90°). None to skip.
            duration (float): Time in seconds (default 0.5).
        """
        if not self._multi_servo:
            return

        # No conversion needed - pass angles directly
        clamped_angles = []
        for index, angle in enumerate(angles):
            if angle is not None:
                clamped_angles.append(_clamp_servo_angle(angle, f"servos.move_all[{index}]"))
            else:
                clamped_angles.append(None)

        try:
            self._multi_servo.move_all_angles_sync(clamped_angles, move_sec=duration)
        except Exception as e:
            log.error(f"Failed to move_all: {e}")

    def center(self):
        """Reset all servos to center (0°)."""
        self.move_all([0] * 8)


class RobotWrapper:
    """
    High-level wrapper for the Robot HAL.
    Matches the API expected by the Blockly/Web IDE.

    Available API (V5.2.1 - ±90° standardized):
        robot.servo[n].angle = x   - Set servo n (0-7) to angle x (±90°)
        robot.buzzer.tone(f, d)    - Play frequency f for d seconds
        robot.buzzer.play(name)    - Play emotion sound
        robot.buzzer.play_song(name) - Play a built-in melody
        robot.display.clear()      - Clear display
        robot.display.text(msg, ...) - Show static or scrolling text
        robot.expression(name)     - Show animated facial expression
        robot.distance.read()      - Read distance in mm
    """

    def __init__(self, hal, cooperative_sleep=None, faces=None, runtime_pipeline=None):
        self._hal = hal
        self._sleep = cooperative_sleep or time.sleep
        self.buzzer = BuzzerWrapper(hal)
        self.display = DisplayWrapper(
            hal,
            runtime_pipeline=runtime_pipeline,
            cooperative_sleep=self._sleep,
        )
        self.distance = DistanceWrapper(hal.distance_sensor)
        
        # Servos: wrap MultiServo to provide list-like access
        # robot.servo[n].angle = x
        self.servo = ServoArrayWrapper(hal.servos)
        self.servos = self.servo  # Alias for plural access (semantic sugar)
        
        # Facial expressions engine. Blockly shares the native face engine when
        # available so idle and uploaded expressions cannot draw concurrently.
        self._faces = faces if faces is not None else AnimatedFaces(hal)

    def expression(self, name: str, duration: float = 2.0):
        """Show an animated facial expression on the display.
        
        Args:
            name: Expression name. Valid options:
                  happy, sad, sleepy, surprising, angry, shy, confusing,
                  scary, exciting, cry, laughing, speaking, idle,
                  embarrassing
            duration: How long to show the expression (default 2 seconds).
        """
        if self._faces:
            try:
                # AnimatedFaces uses play() method
                self._faces.play(name, duration_s=duration)
                # Block for duration to ensure animation completes before next command
                self._sleep(duration)
            except Exception as e:
                log.error(f"Failed to show expression '{name}': {e}")
        else:
            log.warning("AnimatedFaces not available.")

    def request_stop(self):
        """Best-effort stop hook for cooperative executor cancellation."""
        if self._faces:
            self._faces.stop()

        if self.display:
            self.display.stop()

        if self.buzzer:
            self.buzzer.stop(restart_buzzer=True)

        if self._hal:
            for component_name in ("servos",):
                component = getattr(self._hal, component_name, None)
                if component and hasattr(component, "abort"):
                    try:
                        component.abort()
                    except Exception as exc:
                        log.warning("Failed to abort %s during request_stop: %s", component_name, exc)
                elif component and hasattr(component, "off"):
                    try:
                        component.off()
                    except Exception as exc:
                        log.warning("Failed to stop %s during request_stop: %s", component_name, exc)
