[project]
name = "pi0vl53l0x"
version = "2.0.0"
description = "A robust Python driver for the VL53L0X Time-of-Flight distance sensor using pigpio."
authors = [
    {name = "Chihkuang Chang", email = "nilcreator@gmail.com"},
]
dependencies = [
    "click",
    "blessed",
    "ninja_utils",
]
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
pi0vl53l0x = "pi0vl53l0x.__main__:cli"

[project.optional-dependencies]
pi = ["pigpio"]
dev = [
    "pytest",
    "ruff",
]
